# Generated by Django 5.2.17 on 2026-10-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(
                blank=True, default="This is my other default note."
            ),
        ),
    ]
